Jenkinsfile.github, LICENSE, README.adoc, boxes/ncn-common/common.pkr.hcl, boxes/ncn-common/variables.pkr.hcl, boxes/ncn-node-images/k8s/files/resources/common/coredns-affinity.yaml, boxes/ncn-node-images/k8s/files/scripts/common/kubernetes-cloudinit.sh, boxes/ncn-node-images/node-images.pkr.hcl, boxes/ncn-node-images/variables.pkr.hcl, boxes/sles15-base/base.pkr.hcl, boxes/sles15-base/http/autoinst.template.xml, boxes/sles15-base/scripts/kernel.sh, boxes/sles15-base/scripts/qemu.sh, custom/repos.sh, scripts/environment.template, scripts/setup.sh
- Fixes: CASMINST-3535 CASMPET-5121
- Provides: MTL-1512 MTL-1524
- a9fe414 (HEAD -> develop, tag: 0.2.17-1, origin/develop, origin/HEAD) CASMINST-3535 Add MIT license
- 5a657f1 Add pod anti-affinity to coredns pods
- 5ce1554 Remove environment vars that are passed in as packer vars.
- d5461c9 MTL-1524: Alter configuration for local building
- 2fba401 (origin/MTL-1512, MTL-1512) MTL-1524: Alter configuration for local building
=> Latest Pre-Release 0.2.17

boxes/ncn-node-images/k8s/files/scripts/join-spire-on-storage.sh
- Fixes an issue where kubectl fails to connect, most likely due to
KUBECONFIG not being set when the command is run.
- Fixes an issue where ssh instead of sshnh was used, causing the script
to hang while waiting for user input
- Removed the -q on the kubectl command so that we can see the reason
why it thinks spire-server is not ready
- Fixes [CASMTRIAGE-2734](https://connect.us.cray.com/jira/browse/CASMTRIAGE-2734)
This fixes an issue where the kubectl commands fail because KUBECONFIG isn't set. It also fixes a ssh issue where sshnh isn't used with one of the commands, causing a user input prompt to be needed to accept the ssh host key.
- Testing needs to be done on a fresh install.
This script doesn't attempt to join a storage node to spire if it's already joined. …
=> CASMTRIAGE-2734 Fix join spire on storage issues

boxes/ncn-node-images/k8s/files/scripts/join-spire-on-storage.sh
- Fixes an issue where kubectl fails to connect, most likely due to
KUBECONFIG not being set when the command is run.
- Fixes an issue where ssh instead of sshnh was used, causing the script
to hang while waiting for user input
- Removed the -q on the kubectl command so that we can see the reason
why it thinks spire-server is not ready
- Fixes CASMTRIAGE-2734
=> CASMTRIAGE-2734 Fix join spire on storage issues - release 0.2.19

.github/workflows/labeler.yml, Jenkinsfile.github
This will also add a "release" label to any PR made to main.
=> Lock to CSM-RPMs release/1.2 and add Labels

.github/workflows/labeler.yml, Jenkinsfile.github, boxes/ncn-node-images/ceph/files/scripts/common/join_ceph_cluster.sh, boxes/ncn-node-images/ceph/files/scripts/metal/lib-1.5.sh, boxes/ncn-node-images/k8s/files/resources/common/vars.sh
- Fixes CASMINST-3568, CASMINST-3564
Includes the following commits:
```
9a7a59a (HEAD -> develop, tag: 0.2.20-1, origin/develop, origin/HEAD) CASMINST-3568 - Improvements to ceph auto expand/rebuild
266f1f9 Update k8s to 1.20.12 for CVE-2020-28852 fix
```
Smoke tested on redbull
=> Latest Pre-Release 0.2.20

boxes/ncn-common/files/scripts/metal/metal-lib.sh, boxes/ncn-node-images/k8s/files/resources/metal/cloud.cfg.d/00_metalfs_lvm.cfg, boxes/ncn-node-images/k8s/files/resources/metal/cloud.cfg.d/01_metalfs.cfg, boxes/ncn-node-images/k8s/files/resources/metal/cloud.cfg.d/02_metalmounts.cfg
Fixes MTL-1462 
Renames SDU to S3FS.
=> MTL-1462 Remove the SDU partition

boxes/ncn-node-images/k8s/files/scripts/common/kubernetes-cloudinit.sh, boxes/ncn-node-images/k8s/files/scripts/google/lib.sh, boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
- Fixes CASMINST-3573
Creates s3 mountpoints for masters and workers
tested code in craystack
N/A
Medium risk
=> Add s3fs configuration of /var/lib/sdu (masters) and /var/lib/cps-local (workers)

boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
- Fixes https://connect.us.cray.com/jira/browse/CASMINST-3619
Bucket creation happens later
N/A
Low risk
=> Add wait for s3 bucket creation before trying to mount s3fs partition

boxes/ncn-node-images/ceph/files/resources/common/ansible/ceph-rgw-users/roles/ceph-rgw-users/defaults/main.yml, boxes/ncn-node-images/ceph/files/resources/common/ansible/ceph-rgw-users/roles/ceph-rgw-users/tasks/rgw_buckets.yml, boxes/ncn-node-images/k8s/files/scripts/common/kubernetes-cloudinit.sh, boxes/ncn-node-images/k8s/files/scripts/google/lib.sh, boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
- Fixes CASMINST-3627 and CASMHMS-5205 (via csm-rpms)
Includes the following commit:
```
0fd7599 (HEAD -> develop, tag: 0.2.27-1, origin/develop, origin/HEAD) Add admin tools bucket and s3fs mount point on workers
```
=> Latest Pre-Release 0.2.27

boxes/ncn-node-images/k8s/files/resources/common/s3fs/prune-s3fs-cache.sh, boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh, boxes/ncn-node-images/k8s/provisioners/common/install.sh
- Fixes CASMINST-3626
Includes the following commit:
```
f84864b (HEAD -> develop, tag: 0.2.28-1, origin/develop, origin/HEAD, origin/CASMINST-3626-2) Add s3fs cache directory pruning
```
=> Latest Pre-Release 0.2.28

boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
- Fixes https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3652
Update sdu options per sdu testing, also change cps' mount point to include bucket name in the path
Tested in craystack:
```
ncn-w001:~ # mount | grep s3fs
s3fs on /var/lib/cps-local/boot-images type fuse.s3fs (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
```
```
ncn-m002:~ # cat /etc/fstab  | grep sdu
sds /var/lib/sdu fuse.s3fs _netdev,allow_other,passwd_file=/root/.sds.s3fs,url=http://ncn-s001:8080,use_path_request_style,use_cache=/tmp,check_cache_dir_exist=true,uid=2370,gid=2370,umask=0007,allow_other,nonempty 0 0
```
N/A
Low risk
=> Set sdu specific s3fs mount opts and add bucket name to cps mount point

.github/CODEOWNERS, .github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/docs.md, .github/ISSUE_TEMPLATE/rfe.md, .github/PULL_REQUEST_TEMPLATE.md, .github/greetings.yml, .github/labeler.yml, .github/workflows/labeler.yml, .github/workflows/merge_strategy.yml, .github/workflows/stale.yml
=> Sync .github and fix labeler

.github/PULL_REQUEST_TEMPLATE.md
The change _in this repo_ is for a typo.  The important changes in this image build came from changes to csm-rpms:
* CASMINST-2549: Add openssh packages to prevent dependency conflict 
* Align GCP & METAL NCN-COMMON Packages 
* CASMINST-3647 
* CRAYSAT-1241: Add prodmgr RPM to CSM k8s image
=> Latest Pre-Release 0.2.32

boxes/ncn-node-images/storage-ceph/files/scripts/metal/lib-1.5.sh
- Fixes https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3712
N/A
Low
=> Dynamically set size of rgw placement group with num_storage_nodes

Jenkinsfile.github, boxes/ncn-common/common.pkr.hcl, boxes/ncn-common/files/scripts/metal/install.sh, boxes/ncn-common/files/scripts/metal/metal-lib.sh, boxes/ncn-common/provisioners/common/setup.sh, boxes/ncn-common/scripts/kernel-debug.sh, boxes/ncn-common/variables.pkr.hcl, boxes/ncn-node-images/k8s/files/resources/metal/cloud.cfg.d/01_metalfs.cfg, boxes/ncn-node-images/storage-ceph/files/resources/metal/cloud.cfg.d/01_metalfs.cfg, boxes/sles15-base/base.pkr.hcl, boxes/sles15-base/scripts/kernel.sh, boxes/sles15-base/variables.pkr.hcl
- Fixes MTL-1587, MTL-1591
Contains the following commits:
```
20aaa36 (HEAD -> develop, tag: 0.2.37-1, origin/develop, origin/HEAD) MTL-1587 Overwrite any FS Signature
a749df1 (origin/MTL-1591) MTL-1591: Split kernel install to reduce cloud image size.
```
=> Latest Pre-Release 0.2.37

boxes/ncn-common/files/resources/common/cloud.cfg, boxes/ncn-common/files/resources/common/cloud/templates/cloud-init-network.tmpl
This was previously merged here:
https://github.com/Cray-HPE/node-image-build/pull/141
And then aliens came along and erased its existence, leaving no
trace.  Re-introduce the code.
- Fixes #CASMTRIAGE-2793
=> CASMTRIAGE-2793: Disable Network Activation

Jenkinsfile.github, boxes/ncn-common/files/scripts/metal/metal-lib.sh
- Fixes in-repo: CASMINST-3803, CASMINST-3669
- Fixes via csm-rpms:  CASMHMS-5310, CASMHMS-5317, New loftsman rpm
=> Latest Prerelease 0.2.42

boxes/ncn-node-images/storage-ceph/files/scripts/common/pre-load-images.sh
This was fixed in lts 1.0 but not carried over into develop
- Fixes #159 
- Requires #
- Relates to #
=> Casminst-3827 - Fix container image path

boxes/ncn-node-images/k8s/files/scripts/common/apply-networking-manifests.sh, boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
New release for CASMTRIAGE-2912
=> CASMTRIAGE-2912

boxes/ncn-node-images/storage-ceph/files/scripts/common/storage-ceph-cloudinit.sh
Fixes to casminst-3857
- Fixes #
- Requires #
- Relates to #
=> Fixing missing quotes

boxes/ncn-common/files/scripts/metal/metal-lib.sh
Safely handle the case where there are no boot entries in the rbbs
files.  When concatenating bbs and rbbs entries, always attempt to
remove trailing commas.  There will be a trailing comma to remove
in the case where $rbbs is empty.  We were already doing this for
$bbs and $rbbs, but not for the "$bbs,$rbbs" concatenation.
- Fixes MTL-1609
✅
=> MTL-1609: handle the case where rbbs* are empty

boxes/ncn-common/files/resources/common/cloud.cfg, boxes/ncn-node-images/storage-ceph/files/scripts/common/pre-load-images.sh, boxes/ncn-node-images/storage-ceph/files/scripts/common/storage-ceph-cloudinit.sh, boxes/ncn-node-images/storage-ceph/files/scripts/metal/lib-1.5.sh, boxes/ncn-node-images/storage-ceph/provisioners/common/install.sh
- Fixes [CASMPET-5328](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5328)
=> Latest Prerelease 0.2.54

Jenkinsfile.github
We can't confirm this works as desired on `main` until this merges.  We *can* confirm that a branch build does *not* rebuild every day.
=> Build main daily

boxes/ncn-common/files/resources/common/cloud/templates/resolv.conf.tmpl
- Fixes [CASMTRIAGE-3006](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3006)
- Requires #
- Relates to [CAST-26549](https://jira-pro.its.hpecorp.net:8443/browse/CAST-26549)
=> CASMTRIAGE-3006: Add options single-request-reopen to resolv.conf

boxes/ncn-node-images/storage-ceph/files/scripts/common/pre-load-images.sh, boxes/ncn-node-images/storage-ceph/provisioners/common/install.sh
move container image pulls to algol60 from arti
- Fixes # CASMINST-4052
=> Casminst 4052

boxes/ncn-common/files/scripts/metal/net-init.sh
Contains [MTL-1626](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1626)
=> Pre-Release of 0.2.59

boxes/ncn-node-images/k8s/files/scripts/common/kubernetes-cloudinit.sh
- Fixes [CASMTRIAGE-3068](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3068)
Contains the following commit:
```
6ac79e0 (HEAD -> develop, tag: 0.2.63-1, origin/develop, origin/HEAD) Point token cert refresh script at kube config file
```
=> Pre-release of 0.2.63

Jenkinsfile.github
Disables the pit build as a workaround to building the other layers.
=> MTL-1639: Disable pit-common build

boxes/ncn-node-images/provisioners/metal/security.sh
=> MTL-1647: don't hard code the number of days field

Jenkinsfile.github
- Fixes [MTL-1639](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1639)
A version of Chrony was outdated and causing issues with the build process.
=> MTL-1639 - Fix pit-common image builds

Jenkinsfile.github, boxes/ncn-common/common.pkr.hcl, boxes/ncn-common/provisioners/common/install.sh, boxes/ncn-common/provisioners/common/setup.sh, boxes/ncn-common/provisioners/google/setup.sh, boxes/ncn-common/scripts/kernel.sh, boxes/ncn-common/variables.pkr.hcl, boxes/ncn-node-images/node-images.pkr.hcl, boxes/pit-common/pit-common.pkr.hcl, boxes/pit-common/provisioners/google/setup.sh, boxes/pit-common/provisioners/pit/kernel.sh, boxes/pit-common/variables.pkr.hcl, boxes/sles15-base/base.pkr.hcl, boxes/sles15-base/http/autoinst.template.xml, boxes/sles15-base/scripts/cleanup.sh, boxes/sles15-base/scripts/qemu.sh, boxes/sles15-base/scripts/virtualbox.sh, boxes/sles15-base/scripts/wait-for-autoyast-completion.sh, boxes/sles15-base/variables.pkr.hcl
Moves items from base layer into the common layer so that we can eventually stop rebuilding the base layer with every change to subsequent layers.
- Fixes [MTL-1667](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1667)
=> MTL-1667: Move base layer steps to common layer.

vendor/github.com/Cray-HPE/csm-rpms/packages/compute-node.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/metal.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-kubernetes/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/metal.packages
Builds with the latest csm-rpms:main branch.
This *does not* incorporate updates from MTL-1682.
=> Build against latest main

Jenkinsfile.github
- Fixes [MTL-1701](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1701)
Fixes tagging builds that could not find the base release because it had not been built.
=> MTL-1701: Gate base and common releases on build flags.

.github/workflows/merge-strategy.yml
- Fixes #
- Requires #
- Relates to #
=> Merge blocker fix or removal

boxes/ncn-node-images/storage-ceph/files/scripts/common/pre-load-images.sh, boxes/ncn-node-images/storage-ceph/files/scripts/common/storage-ceph-cloudinit.sh, boxes/ncn-node-images/storage-ceph/files/scripts/google/lib.sh, boxes/ncn-node-images/storage-ceph/files/scripts/metal/lib.sh
Fixes to 1.3 vshasta storage image
- Fixes # CASMPET-5580
=> CASMPET-5580

boxes/ncn-node-images/k8s/files/scripts/common/kubernetes-cloudinit.sh
- Fixes # CASMTRIAGE-3280
We tracked down the root cause of weave split-brain on gamora.  The issue was caused by weave pods starting up before enough of the nodes have joined the cluster.   More details in https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3280.   To fix this, we are waiting for a quorum of nodes to join the cluster before applying the network manifests.   We tried this process manually on gamora and we were able to see the expected results in the weave logs showing that they had a enough peers in the peer list to avoid splitting the two masters into two separate seed groups.
- [N/A] I have included documentation in my PR (or it is not required)
This code will be smoke tested on gamora to mitigate risk.
=> CASMTRIAGE-3280: Wait for a quorum of nodes to join before applying network manifests

vendor/github.com/Cray-HPE/csm-rpms/.github/workflows/shellcheck.yml, vendor/github.com/Cray-HPE/csm-rpms/build/create-index.sh, vendor/github.com/Cray-HPE/csm-rpms/build/update-packages.sh, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/metal.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/scripts/rpm-functions.sh, vendor/github.com/Cray-HPE/csm-rpms/scripts/update-package-versions.sh
=> CASMINST-4600 develop

vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages
Includes:
- MTL-1747
- CASMNST-1548
=> Csm rpms update 1.2

vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/repos/cray.repos
- [MTL-1747](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1747)
- [CASMNET-1519](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1519)
- [CASMNET-1541](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1541)
- [CASMNET-1548](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1548)
- [CASMINST-4653](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4653)
=> CSM RPMs Update (main)

vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/repos/cray.repos
- [CASMNET-1519](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1519)
- [CASMNET-1541](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1541)
- [CASMNET-1548](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1548)
- [CASMINST-4653](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4653)
=> CSM RPMs Update (1.2)

vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-kubernetes/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/repos/cray.repos
Includes:
- https://github.com/Cray-HPE/csm-rpms/pull/416
- https://github.com/Cray-HPE/csm-rpms/pull/418
=> CASMINST-4667 canu and  HPCCHT3-3210 sdu

vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages
Includes:
- https://github.com/Cray-HPE/csm-rpms/pull/417
=> CASMINST-4667 canu

vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages
- Fixes CASMINST-4659
This pulls in a newer csm-rpms.
=> CASMINST 4659

boxes/ncn-common/files/tests/common/goss-image-common.yaml, boxes/ncn-common/provisioners/common/install.sh
=> CASMTRIAGE-3391: enable goss-servers

vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages
=> Vendor update canu

vendor/github.com/Cray-HPE/csm-rpms/repos/suse.template.repos
- Fixes CASMINST-925, CASMINST-3912, CASMINST-4695, CASMTRIAGE-3322
- Requires #
- Relates to #
=> Git Vendor Update for CASMINST-925, CASMINST-3912, CASMINST-4695, CASMTRIAGE-3322

.github/workflows/shellcheck.yml, boxes/ncn-common/files/scripts/metal/metal-lib.sh, vendor/github.com/Cray-HPE/csm-rpms/build/create-index.sh, vendor/github.com/Cray-HPE/csm-rpms/build/update-packages.sh, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/scripts/rpm-functions.sh, vendor/github.com/Cray-HPE/csm-rpms/scripts/update-package-versions.sh
Add canu to the list of packages that gets installed via cloud-init
Pairs with https://github.com/Cray-HPE/csm/pull/894
- Relates to CASMNET-1591
=> CASMNET-1591: Add canu to the list of packages installed via cloud-init

boxes/ncn-common/files/scripts/metal/metal-lib.sh
Canu recently moved from the sp2 repo to the sp3 repo. This script
was not searching the sp3 repo. This commit rectifies the situation.
- Fixes CASMINST-4791
=> CASMINST-4791: search sp3 repo in addition to sp2

Jenkinsfile.github, vendor/github.com/Cray-HPE/metal-provision/.github/workflows/lint.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-install/defaults/main.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-install/tasks/common.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-install/tasks/gcp.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-install/tasks/metal.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/files/srv/cray/tests/common/goss-image-common.yaml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/files/srv/cray/tests/metal/goss-image-common.yaml
- Fixes MTL-1800
This pulls in a new metal-provision that has better daemon handling for NCN common and NCN metal.
=> MTL-1800 daemons

vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/defaults/main.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/tasks/gcp.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/tasks/metal.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-team/defaults/main.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-team/tasks/common.yml
This actually fixes MTL-1800.
This pulls in an updated metal-provisioning repository that disables metal-iptables.
=> MTL-1800 follow up 2

vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-kubernetes/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/repos/cray.repos
This just pulls in recent CSM-RPMs changes.
=> CASMCMS-7876

boxes/ncn-node-images/kubernetes/files/tests/common/goss-image-common.yaml, boxes/ncn-node-images/provisioners/metal/cleanup.sh, boxes/ncn-node-images/storage-ceph/files/tests/common/goss-image-common.yaml
=> MTL-1812: cease including ssh host keys in the image

.github/PULL_REQUEST_TEMPLATE.md
Tidy up the whitespace in the PR template.
=> Remove whitespace from template

.github/PULL_REQUEST_TEMPLATE.md, boxes/ncn-node-images/kubernetes/files/tests/common/goss-image-common.yaml, boxes/ncn-node-images/provisioners/metal/cleanup.sh, boxes/ncn-node-images/storage-ceph/files/tests/common/goss-image-common.yaml
Includes the following commits:
- 7912d693e (HEAD -> develop, origin/new-pr-template-2, origin/develop, origin/HEAD, new-pr-template-2) Remove whitespace from template
- 63e9c1518 (origin/new-pr-template, new-pr-template) Updating template
- 7b5312192 (tag: 0.3.12) MTL-1812: add goss check to ensure no host keys are present
- adbc76400 MTL-1812: remove ssh host keys
- 5a857ad5a Add missing echos, add -v flag to rm invocations
=> Latest 0.3.12 Release

Jenkinsfile.github, scripts/google/import.sh
- Fixes: MTL-1823
The GA ISO is now out, this commit switches us from the BETA to the GA ISO.
=> MTL-1823 SLES15SP4 GA

vendor/github.com/Cray-HPE/csm-rpms/.github/PULL_REQUEST_TEMPLATE.md, vendor/github.com/Cray-HPE/csm-rpms/README.asc, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/google.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/metal.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-kubernetes/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-kubernetes/metal.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/google.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/metal.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-storage-ceph/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-storage-ceph/google.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-storage-ceph/metal.packages
- Fixes: MTL-1752
- Relates to: [SHASTAOS-1136](https://jira-pro.its.hpecorp.net:8443/browse/SHASTAOS-1136)
=> MTL-1752: add dkms to the NCN common layer

boxes/ncn-node-images/storage-ceph/files/scripts/common/cubs_tool.py
Adding cubs_tool.py so the image.  this is a wrapper script to assist with the ceph software upgrade
- Fixes: CASMPET-5484
- Requires:
- Relates to:
- [x ] I have included documentation in my PR (or it is not required)
This is just putting the script in place.
=> CASMPET-5484

Jenkinsfile.github
- Relates to: VSHA-414
Now that the `Jenkinsfile` is more parallelized and pit-common is used in GCP for vshasta, we should build it.
=> VSHA-414 Enable PIT Common

boxes/ncn-node-images/storage-ceph/provisioners/common/install.sh
These often fail.  Wrap them in retry logic.  The retry logic
was borrowed from assets.sh in the CSM repo.
- Relates to: MTL-1699
=> MTL-1699: add retry to "podman pull" calls

boxes/ncn-node-images/storage-ceph/provisioners/common/install.sh, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/metal.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-kubernetes/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/metal.packages, vendor/github.com/Cray-HPE/csm-rpms/repos/cray.repos
Brings in the following csm-rpms changes:
- https://github.com/Cray-HPE/csm-rpms/pull/531
- https://github.com/Cray-HPE/csm-rpms/pull/532
- https://github.com/Cray-HPE/csm-rpms/pull/533
- https://github.com/Cray-HPE/csm-rpms/pull/534
- https://github.com/Cray-HPE/csm-rpms/pull/535
- https://github.com/Cray-HPE/csm-rpms/pull/537
- https://github.com/Cray-HPE/csm-rpms/pull/536
=> CASMINST-5103 MTL-1858 MTL-1865 CASMINST-4903 CASMINST-4278 CASMINST-5161

Jenkinsfile.github, boxes/ncn-node-images/kubernetes/files/tests/common/kubernetes-tests.yml, boxes/ncn-node-images/node-images.pkr.hcl, boxes/ncn-node-images/storage-ceph/files/tests/common/storage-ceph-tests.yml, boxes/ncn-node-images/storage-ceph/provisioners/common/install.sh, boxes/pit-common/files/tests/common/pit-common-tests.yml, boxes/pit-common/pit-common.pkr.hcl, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/metal.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-kubernetes/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/metal.packages, vendor/github.com/Cray-HPE/csm-rpms/repos/cray.repos
- Relates to: VSHA-220, VSHA-421
- Improve build tests
- Add validation before liveCD tests
When builds are complete the build pipeline should automatically test those images
The image should be launched, and Goss tests should be run to validate the image contents.
=> VSHA-420 - Add goss tests to pit, ceph and kubernetes images

vendor/github.com/Cray-HPE/csm-rpms/packages/compute-node.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-kubernetes/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/repos/cray.repos
Fixes:
- https://github.com/Cray-HPE/csm-rpms/pull/541
- https://github.com/Cray-HPE/csm-rpms/pull/540
- https://github.com/Cray-HPE/csm-rpms/pull/542
- https://github.com/Cray-HPE/csm-rpms/pull/544
- https://github.com/Cray-HPE/csm-rpms/pull/543
=> Vendor update

vendor/github.com/Cray-HPE/csm-rpms/packages/compute-node.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/extra.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-kubernetes/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/repos/cray.repos, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common/defaults/main.yml
- Fixes: CASMINST-4884, CASMCMS-8090, CASMCMS-7971
=> Vendor updates 081122

boxes/ncn-common/provisioners/common/cleanup.sh, boxes/ncn-node-images/node-images.pkr.hcl, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common/files/tests/common/ncn-common-tests.yml
=> MTL-1907: downgrade kernel for SSHOT, COS, et al

vendor/github.com/Cray-HPE/csm-rpms/packages/compute-node.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-kubernetes/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages
- Fixes: CASMHMS-5351 CASMINST-5240
=> CASMHMS-5351 CASMINST-5240 vendor update

Jenkinsfile.github
Wrong download dir for partial builds.
=> Use the right base-dir

Jenkinsfile.github, boxes/ncn-node-images/kubernetes/provisioners/common/install.sh, vendor/github.com/Cray-HPE/metal-provision/pb_ncn_common.yml, vendor/github.com/Cray-HPE/metal-provision/pb_ncn_common_team.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common/files/scripts/common/create-ims-initrd.sh, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common/files/scripts/metal/metal-lib.sh
- Fixes: MTL-1923
- Includes: MTL-1926
=> MTL-1923: fix broken IMS initrd script

vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common/files/scripts/common/create-ims-initrd.sh
Fixes: [MTL-1930](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1930) - fix for create-ims-initrd.sh
=> MTL-1930: metal-provision vendor update

vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-compute/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-kubernetes/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-pre-install-toolkit/base.packages
- Fixes: CASMCMS-8192, CASMCMS-8193
=> CASMCMS-8192, CASMCMS-8193: csm-rpms vendor update
