boxes/ncn-node-images/k8s/files/scripts/join-spire-on-storage.sh
- Fixes [CASMINST-3539](https://connect.us.cray.com/jira/browse/CASMINST-3539)
- 
This adds a check to the join-spire-on-storage.sh script to only attempt to join the storage nodes from ncn-m001. If this isn't here then it'll cause a 5 minute boot delay on any NCNs that boot up prior to spire-server being available.
Validated that the new check works.
Script won't attempt to join a storage node that's already joined.
If a node with the hostname ncn-m001 never starts then this script won't run and the storage nodes will never get joined to spire without manual intervention.
=> CASMINST-3539 Add check to validate script runs on ncn-m001

boxes/ncn-common/files/scripts/metal/metal-lib.sh
- Fixes CASMINST-3538
Adding platform-utils back in metal-lib.sh for 1.2
Code change finds rpm on wasp:
https://packages.local/repository/csm-sle-15sp2/noarch/platform-utils-1.2.4-1.noarch.rpm
N/A
N/A
=> Add platform-utils rpm to metal-lib.sh (missed from 1.0)

boxes/ncn-common/files/scripts/metal/metal-lib.sh, boxes/ncn-node-images/k8s/files/scripts/join-spire-on-storage.sh
- Fixes CASMINST-3538, CASMINST-3539
```
8ec558f (HEAD -> develop, tag: 0.2.18-2, origin/develop, origin/HEAD) Add platform-utils rpm to metal-lib.sh (missed from 1.0)
c03caea (tag: 0.2.18-1) CASMINST-3539 Add check to validate script runs on ncn-m001
```
smoke-tested on redbull
=> Latest Pre-Release 0.2.18

boxes/ncn-node-images/k8s/files/resources/common/vars.sh
- Fixes https://connect.us.cray.com/jira/browse/CASMINST-3564
Bump patch version for 1.2 to pull in fix for CVE-2020-28852
Smoke tested in craystack:
```
ncn-m001:~ # kubectl get nodes
NAME       STATUS   ROLES                  AGE   VERSION
ncn-m001   Ready    control-plane,master   46m   v1.20.12
ncn-m002   Ready    control-plane,master   48m   v1.20.12
ncn-m003   Ready    control-plane,master   46m   v1.20.12
ncn-w001   Ready    <none>                 46m   v1.20.12
ncn-w002   Ready    <none>                 46m   v1.20.12
ncn-w003   Ready    <none>                 46m   v1.20.12
```
N/A
Low risk
=> Update k8s to 1.20.12 for CVE-2020-28852 fix

boxes/ncn-node-images/ceph/files/scripts/common/join_ceph_cluster.sh, boxes/ncn-node-images/ceph/files/scripts/metal/lib-1.5.sh, boxes/ncn-node-images/k8s/files/resources/common/vars.sh
Includes:
- Fixes to the join_ceph_cluster.sh script to avoid extra iterations
- Fixes to address if the ceph node is a designated a ceph-mon node
- Additional ceph device monitoring to allow for failure prediction
- Fixes # CASMINST-3568
- improvement
This is to support the storage node for expansion and/or rebuild in place.  It enables the node to run a script via cfs or a runcmd to join the ceph cluster as a new or existing node.  If it is an existing node it will utilize present lvms on the OSDs so we do not have to wipe those if we are just rebuilding in place.  This should also help cut down the time of the image based upgrade.
This will only redeploy existing services if accidentally run
This is not run automatically.  so poses not risk.
=> CASMINST-3568 - Improvements to ceph auto expand/rebuild

boxes/ncn-common/provisioners/common/install.sh
The SSHOT-supplied lldpad automatically started the lldpad service.
With the SSHOT software removed from NCNs, we need to start it
explicitly.
- Fixes MTL-1553
Smoke tested on redbull.  Booted from disk on redbull.
Requires: https://github.com/Cray-HPE/csm-rpms/pull/119
=> MTL-1553: explicitly start lldpad

boxes/ncn-common/files/scripts/metal/metal-lib.sh
- Fixes MTL-1559
The regex for cleaning old menu items was not refactored when the menu
item name was refactored. This lead to duplicates spawninig in
efibootmgr.
This also fixes a bad operateror that was overriding the name variable
for the grub2 menu.
=> MTL-1559 Update the regex for removing boot items

boxes/ncn-common/files/scripts/metal/metal-lib.sh, boxes/ncn-common/provisioners/common/install.sh, boxes/ncn-node-images/k8s/files/resources/metal/cloud.cfg.d/00_metalfs_lvm.cfg, boxes/ncn-node-images/k8s/files/resources/metal/cloud.cfg.d/01_metalfs.cfg, boxes/ncn-node-images/k8s/files/resources/metal/cloud.cfg.d/02_metalmounts.cfg
- Fixes  MTL-1462 MTL-1553 MTL-1559
- 6184bce (HEAD -> develop, tag: 0.2.21-2, origin/develop, origin/MTL-1462-remove-sdu-partition, origin/HEAD, MTL-1462-remove-sdu-partition) MTL-1462 Swap SDU partition for S3FS
- 048cb01 (tag: 0.2.21-1, origin/MTL-1559-fix-refactored-removal, MTL-1559-fix-refactored-removal) MTL-1559 Update the regex for removing boot items
- 3e0cd8b (origin/MTL-1553) MTL-1553: explicitly start lldpad
=> Latest Pre-Release 0.2.21

boxes/ncn-node-images/k8s/files/resources/metal/cloud.cfg.d/01_metalfs.cfg
- Fixes MTL-1566
- Relates to MTL-1462
This file is using CRAYS3FS when it should be using CRAYS3CACHE. With the misalignment the following error is seen in cloud-init and the drive is not formatted:
```bash
[  135.016353] cloud-init[11332]: Device /dev/disk/by-id/dm-name-metalvg0-CRAYS3FS did not exist and was not created with a udevadm settle.
```
=> MTL-1566 Fix misaligned disk label for CRAYS3CACHE

boxes/ncn-node-images/k8s/files/resources/metal/cloud.cfg.d/01_metalfs.cfg, boxes/ncn-node-images/k8s/files/scripts/common/kubernetes-cloudinit.sh, boxes/ncn-node-images/k8s/files/scripts/google/lib.sh, boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
- Fixes MTL-1566, CASMINST-3573
```
07269f6 (HEAD -> develop, tag: 0.2.22-2, origin/develop, origin/HEAD) MTL-1566 Fix misaligned disk label for CRAYS3CACHE
1c59da6 (tag: 0.2.22-1, origin/CASMINST-3573) Add s3fs configuration of /var/lib/sdu (masters) and /var/lib/cps-local (workers)
```
=> Latest Pre-Release 0.2.22

boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
Wait for secret to get created before mounting s3fs
- Fixes CASMINST-3614
Need secret before mount
N/A
Low risk
=> Add wait for s3fs secret before mounting directory

boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
- Fixes CASMINST-3614 - Add wait for s3fs secret before mounting directory
Contains the following commit:
```
5c57a67 (HEAD -> develop, tag: 0.2.23-1, origin/develop, origin/HEAD) Add wait for s3fs secret before mounting directory
```
=> Latest Pre-Release 0.2.23

boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
- Fixes CASMINST-3619 Add wait for s3 bucket creation before trying to mount s3fs partition
Contains the following commits:
```
b7db484 (HEAD -> develop, tag: 0.2.24-1, origin/develop, origin/HEAD) Add wait for s3 bucket creation before trying to mount s3fs partition
```
=> Latest Pre-Release 0.2.24

boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
=#### Summary and Scope
- Fixes https://connect.us.cray.com/jira/browse/CASMTRIAGE-2764
We weren't sure if the recent s3fs changes where they immediately mount an s3fs dir as soon as the corresponding bucket is created, but by changing what the k8s nodes wait for (csi config map -- which occurs after all rgw config is done) seems to have fixed the issue.  Tested on redbull:
```
ncn-s001:~ # radosgw-admin buckets list
[
"nmd",
"badger",
"postgres-backup",
"ssi",
"prs",
"sls",
"wlm",
"ssm",
"sds",
"sat",
"velero",
"sma",
"alc",
"install-artifacts",
"benji-backups",
"vbis",
"fw-update",
"ssd",
"ims",
"etcd-backup",
"boot-images"
]
```
```
ncn-w002:~ # mount | grep s3
/dev/mapper/metalvg0-CRAYS3CACHE on /var/lib/s3fs_cache type ext4 (rw,relatime)
s3fs on …
```
=> Delay s3fs bucket mounting until ceph is really done with rgw config

boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
- Fixes https://connect.us.cray.com/jira/browse/CASMTRIAGE-2764
Contains the following commits:
```
d69c3fc (HEAD -> develop, tag: 0.2.25-1, origin/develop, origin/HEAD) Attempt to delay s3fs bucket mounting until ceph is really done with rgw config
```
=> Latest Pre-Release 0.2.25

boxes/ncn-node-images/ceph/files/resources/common/ansible/ceph-rgw-users/roles/ceph-rgw-users/defaults/main.yml, boxes/ncn-node-images/ceph/files/resources/common/ansible/ceph-rgw-users/roles/ceph-rgw-users/tasks/rgw_buckets.yml, boxes/ncn-node-images/k8s/files/scripts/common/kubernetes-cloudinit.sh, boxes/ncn-node-images/k8s/files/scripts/google/lib.sh, boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
- Fixes https://connect.us.cray.com/jira/browse/CASMINST-3627
Add admin-tools bucket for ssi and other admin tools (and s3fs mount point).  Also removing unused buckets (ssi, vbis, benji-backups). 
Craystack:
```
ncn-s001:~ # radosgw-admin bucket list
[
"nmd",
"badger",
"postgres-backup",
"prs",
"sls",
"wlm",
"ssm",
"sds",
"sat",
"velero",
"sma",
"install-artifacts",
"fw-update",
"ssd",
"admin-tools",
"ims",
"etcd-backup",
"boot-images"
]
```
```
ncn-m001:/var/lib/admin-tools # mount | grep s3fs
s3fs on /var/lib/sdu type fuse.s3fs (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
s3fs on /var/lib/admin-tools type fuse.s3fs (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
```
```
ncn-w001:~ # mount | grep s3fs
s3fs on /var/lib/cps-local type fuse.s3fs …
```
=> Add admin tools bucket and s3fs mount point on workers

boxes/ncn-node-images/k8s/files/resources/common/s3fs/prune-s3fs-cache.sh, boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh, boxes/ncn-node-images/k8s/provisioners/common/install.sh
- Fixes https://connect.us.cray.com/jira/browse/CASMINST-3626
Adding cache dir prune script and cronjobs to call script.
Tested in craystack, cronjobs are there, script calls working:
```
ncn-m002:/etc/cron.d # grep prune-s3fs /var/log/messages
2021-11-30T20:00:01.661030+00:00 ncn CRON[18986]: (root) CMD (/usr/bin/prune-s3fs-cache.sh admin-tools /tmp 5368709120)
```
N/A
=> Add s3fs cache directory pruning

.github/PULL_REQUEST_TEMPLATE.md
This change is strictly to the PR template.
The "internal system checkbox" was split-up into the two spheres we deliver for; metal, and vshasta.
=> testing checkboxes for vshasta and metal

boxes/ncn-node-images/storage-ceph/files/scripts/common/ceph-enable-services.sh
This will address the systemd_unit enable for cluster larger than 3
- Fixes CASMINST-3650
On nodes that do not have the credentials to run ceph commands the ceph enable script will not work.  
This is idempotent.
=> CASMINST-3650 - Fix for ceph-enable-services

boxes/ncn-node-images/k8s/files/resources/metal/cloud.cfg.d/00_metalfs_lvm.cfg
- Fixes MTL-1562
This change results in striping the final partition on each disk in the RAID.
_Before_:
- Partition 1: Mirror, FSLABEL=BOOTRAID
- Partition 2: Mirror, FSLABEL=SQFSRAID
- Partition 3: Mirror, FSLABEL=ROOTRAID
- Partition 4: Mirror, FSLABEL=AUX
_After_:
- Partition 1: Mirror, FSLABEL=BOOTRAID
- Partition 2: Mirror, FSLABEL=SQFSRAID
- Partition 3: Mirror, FSLABEL=ROOTRAID
- Partition 4: Stripe, FSLABEL=AUX
https://github.com/Cray-HPE/docs-csm/pull/639
Low risk. Installs & Upgrades will be able to wipe and adopt this without issue.
=> MTL-1562 Take advantage of the stripe

boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
- Fixes https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3652
Adding the immutable flag to /var/lib/sdu didn't work on smoke test, reverting that piece.
N/A
Low risk, already broken
=> Remove chattr for /var/lib/sdu -- will solve differently

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/labeler.yml, boxes/ncn-node-images/k8s/files/resources/metal/cloud.cfg.d/00_metalfs_lvm.cfg, boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
Latest pre-release.
- a152506 (HEAD -> develop, tag: 0.2.30-2, origin/develop, origin/HEAD, origin/CASMINST-3652-2, CASMINST-3652-2) Remove chattr for /var/lib/sdu -- will solve differently
- 31ca355 (origin/MTL-1562-double-s3fs-size, MTL-1562-double-s3fs-size) MTL-1562 Take advantage of the stripe
- cb6a5ca (tag: 0.2.30-1, origin/CASMINST-3652) Set sdu specific s3fs mount opts and add bucket name to cps mount point
=> Latest Pre-Release 0.2.30

boxes/ncn-node-images/storage-ceph/files/scripts/metal/lib-1.5.sh
- Fixes https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3681
Enable haproxy and goss tests on nodes greater than 3
N/A
Low
=> Copy /etc/ceph contents to all ceph nodes for haproxy config and goss tests

boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
Also fix setting check_cache_dir_exist in prep for s3fs 1.90
- Fixes https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3667
Update sdu mount options per testing, fix option to check_cache_dir_exist (not used yet -- but will be when we have 1.90)
```
ncn-m001:~ # mount | grep s3fs
s3fs on /var/opt/cray/sdu/collection-mount type fuse.s3fs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
s3fs on /var/lib/admin-tools type fuse.s3fs (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
```
```
ncn-m001:~ # cat /etc/fstab | grep fuse
sds /var/opt/cray/sdu/collection-mount fuse.s3fs _netdev,allow_other,passwd_file=/root/.sds.s3fs,url=http://ncn-s001:8080,use_path_request_style,use_cache=/tmp,check_cache_dir_exist,uid=2370,gid=2370,umask=0007,allow_other 0 0 …
```
=> Remove nonempty option and change sdu mount point

boxes/ncn-common/files/scripts/metal/metal-lib.sh
- Fixes MTL-1583
This fixes two things:
1. It ensures lldpad is active; the daemon will start if it isn't already.
2. This enables and configures LLDP on mgmt, sun, and bond NICs.
Observe, ncn-s00[1-3] are reporting hostnames and advertising correctly _after_ enabling `adminStatus=rxtx` and `sysName enableTx=yes` on each NCN.
```bash
sw-spine-001 [mlag-domain: master] # sh lldp remote
--------------------------------------------------------------------------------
Local Interface      Device ID            Port ID              System Name
--------------------------------------------------------------------------------
Eth1/1 (Mpo1)        b8:59:9f:fe:49:d4    b8:59:9f:fe:49:d4    Not Advertised
Eth1/2 (Mpo2)        b8:59:9f:f9:1c:8e    b8:59:9f:f9:1c:8e    Not …
```
=> MTL-1583 lldpad not starting

boxes/ncn-common/files/scripts/metal/metal-lib.sh, boxes/ncn-node-images/storage-ceph/files/scripts/common/join_ceph_cluster.sh, boxes/ncn-node-images/storage-ceph/files/scripts/common/storage-ceph-cloudinit.sh
This will help address the ceph service checks and the patch to distribute the admin across all nodes
- Fixes # CASMPET-5208
- Bug/Security
This change creates a read-only ceph client for use with the ceph-services script.
The admin credentials were distributed across ceph hosts which is against best practices for ceph security. 
If run again, it will create and distribute a new keyring.  i.e. this is safe to run as many times as we want as long as the keyrings are distributed.  But really, this script should only run once at install and never again.
=> CASMPET-5208 - create and distribute a ceph read-only keyring

boxes/ncn-common/files/scripts/metal/install.sh, boxes/ncn-common/files/scripts/metal/net-init.sh
- Fixes MTL-1540
- Relates to CASMTRIAGE-2793
Now if metadata is missing the net-init.sh script will exit, preventing
needless tampering with malformed data.
Additionally it was discovered that craysys looses its cache if the
network topology (or anything pertaining to the cloud-init data load) is
changed post hoc. This ensures we reload metadata, allowing any
subsequent calls to craysys to work.
Lastly we re-order the install.sh script to ensure we write a default
route as soon as possible, before we touch the MTL IPs.
=> MTL-1540 Harden net-init

boxes/ncn-common/files/scripts/metal/install.sh, boxes/ncn-common/files/scripts/metal/net-init.sh
- Fixes MTL-1588
The cold reset is very harsh on servers where a warm reset is
sufficient. On HPE, a warm reset will kick-over DHCP/static IPsrcs and
return faster.
This change pivots HPE servers to always warm reset instead of cold
resetting.
=> MTL-1588 Remove Risk of Connection Loss

boxes/ncn-common/files/resources/common/cloud.cfg, boxes/ncn-common/files/resources/common/cloud/templates/cloud-init-network.tmpl
- Requires https://github.com/Cray-HPE/metal-ipxe/pull/26
- Relates to CASMTRIAGE-2793
cloud-init will attempt to UP the network during its own startup,
however the network is already UP at this point. The re-UP of the
network causes the NCN's bond to go down and then UP, this can affect
STP blocks on Arubas. Specifically we see STP blocks in storage nodes,
after they've booted successfully they may or may not actually start
cloud-init. In those cases cloud-init falls to a fallback datasource,
and becomes difficult to recover.
Testing yielded successful cloud-init runs on HPE systems with Arubas where previously cloud-init was struggling.
- surtur storage nodes all booted successfully, these had previously been flaking when cloud-init started _after_ using the …
=> CASMTRIAGE-2793 Disable Network Activation

boxes/ncn-common/files/scripts/metal/install.sh, boxes/ncn-common/files/scripts/metal/net-init.sh
- Fixes MTL-1407 MTL-1590 MTL-1588 MTL-1540 CASMPET-5208 MTL-1586
- Relates to CASMTRIAGE-2793
- dbbeb20 (HEAD -> develop, tag: 0.2.35-5, tag: 0.2.35-4, tag: 0.2.35-3, origin/develop, origin/MTL-1588-mc-reset-warm-for-HPE-only, origin/HEAD, MTL-1588-mc-reset-warm-for-HPE-only) MTL-1588 Remove Risk of Connection Loss
- 0c47963 (tag: 0.2.35-2, origin/MTL-1540-net-init-hardening, MTL-1540-net-init-hardening) MTL-1540 Always reload metadata and add fatal exit
- cd9e918 (tag: 0.2.34-1, tag: 0.2.34, tag: 0.2.33-4, tag: 0.2.33, origin/main, origin/CASMPET-5208, main, CASMPET-5208) Updating join script to fetch the client.ro keyring
- 53055fc CASMPET-5208 - create and distribute a ceph read-only keyring
=> Latest Pre-Release 0.2.35

Jenkinsfile.github, boxes/ncn-common/common.pkr.hcl, boxes/ncn-common/provisioners/common/setup.sh, boxes/ncn-common/scripts/kernel-debug.sh, boxes/ncn-common/variables.pkr.hcl, boxes/sles15-base/base.pkr.hcl, boxes/sles15-base/scripts/kernel.sh, boxes/sles15-base/variables.pkr.hcl
- Fixes the size of cloud images by reducing the size. 
- Switches base build to use Online version of SLES15 ISO. Reducing the size of the download.
- Removes left over code from debugging.
- Converts kernel version to a parameter.
- Adjusts output of base layer to include version string in filename to enable GCP upload locally in addition to build pipeline.
The Packer code splits the install and pinning of the kernel version so that the debug packages are not installed in the base layer, and again not installed for GCP code. 
N/A
N/A
N/A
N/A
=> MTL-1591: Split kernel install to reduce cloud image size

boxes/ncn-common/files/scripts/metal/metal-lib.sh
- Relates to #144 
The helper function for enabling the FS overwrite was broken, the code
had been copy-pasted and not meticulously inspected.
Testing:
```bash
ncn-m003:~ # vim /srv/cray/scripts/metal/metal-lib.sh
ncn-m003:~ # source !$
source /srv/cray/scripts/metal/metal-lib.sh
ncn-m003:~ # enable_fs_overwrite
ncn-m003:~ # cat /etc/cloud/cloud.cfg.d/01_metalfs.cfg
#cloud-config
fs_setup:
- label: CRAYS3CACHE
filesystem: ext4
device: /dev/disk/by-id/dm-name-metalvg0-CRAYS3CACHE
partition: auto
overwrite: true
ncn-m003:~ # remove_fs_overwrite
note: re-running cloud-init will not wipe any LVMs in /dev/md/AUX; to purge these on a re-run, source the metal-lib and invoke enable_fs_overwrite
ncn-m003:~ # cat /etc/cloud/cloud.cfg.d/01_metalfs.cfg
#cloud-config
fs_setup:
- …
```
=> MTL-1587 Fix Helper Function

boxes/sles15-base/variables.pkr.hcl
=> CASMISNT-3780: bump kernel version to match DVS/LNET/NETETH

boxes/ncn-common/files/scripts/metal/metal-lib.sh, boxes/sles15-base/variables.pkr.hcl
Release 0.2.39
Includes the following commit:
```
546ad18 (HEAD -> develop, tag: 0.2.39-1, origin/develop, origin/HEAD, origin/CASMISNT-3780, CASMISNT-3780) CASMISNT-3780: bump kernel version to match DVS/LNET/NETETH
```
=> Latest Pre-Release 0.2.39

boxes/ncn-node-images/k8s/files/scripts/common/kubernetes-cloudinit.sh
Release 0.2.40
- Fixes https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5183
Includes the following commit:
```
5ff2119 (HEAD -> develop, origin/develop, origin/HEAD) Fix cronjob kicker schedule to be once every two hours
```
=> Latest Prerelease 0.2.40

boxes/ncn-node-images/storage-ceph/files/scripts/metal/generate_haproxy_cfg.sh, boxes/ncn-node-images/storage-ceph/files/scripts/metal/lib-1.5.sh, boxes/ncn-node-images/storage-ceph/provisioners/common/install.sh
There is an issue where the haproxy.cfg did not get generated due to
not calling the read-only ceph key on nodes that are nogt monitors.
This is also fixing an issue of missing minimal ceph.conf on nodes that are
not mons.
- Fixes CASMINST-3800
This is only run during fresh install
not having this will cause some inconsistency w/ haproxy on ceph cluster greater than 3
=> CASMINST-3800 Fix issue with rgw on clusters greater than 3

boxes/ncn-common/files/resources/common/cloud.cfg, boxes/ncn-common/files/resources/common/cloud/templates/cloud-init-network.tmpl, boxes/ncn-node-images/storage-ceph/files/scripts/metal/generate_haproxy_cfg.sh, boxes/ncn-node-images/storage-ceph/files/scripts/metal/lib-1.5.sh, boxes/ncn-node-images/storage-ceph/provisioners/common/install.sh
- Fixes CASMINST-3800, CASMINST-3801
Includes the following commits:
```
bf3e264 (HEAD -> develop, tag: 0.2.41-2, origin/develop, origin/HEAD, origin/CASMTRIAGE-2793-redux, CASMTRIAGE-2793-redux) CASMTRIAGE-2793: Disable Network Activation
3ba6ba9 (tag: 0.2.41-1, origin/CASMINST-3800) Including k8s client version bump
54a9edf CASMINST-3800 Fix issue with rgw on clusters greater than 3
```
=> Latest Prerelease 0.2.41

Jenkinsfile.github
- Fixes CASMINST-3803
- Relates to CASMINST-3799
- used by https://github.com/Cray-HPE/csm/pull/369
Kubernetes node image come pre-populated with Kubernetes (and some supplementary) container images. Sometimes during install/upgrade, these images need to be re-downloaded from Nexus. For this purpose, Nexus should also be populated with the same versions of images. This change adds a validation step to `assets.sh` script, which ensures that same version are being shipped with node image and installed in Nexus. To perform validation, we need to expose container image versions as node image artifact properties.
No testing required at node-image-builder side - there's no change in node image itself. Only item properties in Artifactory are getting changed (new properties …
=> CASMINST-3803 Validate node image component versions against Nexus

boxes/ncn-common/files/scripts/metal/metal-lib.sh
At some point in the CSM 1.2 development timeline an SP3 repo was
configured in Nexus.  This appears to no longer be the case.  And
since the RPMs we're installing still live in a repo with sp2 in
the name, check for the existence of the sp2 repo in order to
determine Nexus health.
While we're here, adjust the warning message to be more helpful
in the event Nexus is deemed unhealthy.
- Fixes CASMINST-3669
=> CASMINST-3669: check sp2 repo to determine Nexus health

boxes/ncn-node-images/storage-ceph/files/scripts/common/storage-ceph-cloudinit.sh, boxes/ncn-node-images/storage-ceph/files/scripts/metal/lib-1.5.sh
This will create the client.ro keyring prior to the ansible run on metal
installs, and will conditionally create it if it doesn't exist in the main
storage cloud-init to cover non-metal installs
- Fixes # CASMINST-3825
See summary
n/a
n/a
=> CASMINST-3825 - Fix a timing issue with ro ceph keyring creation

boxes/ncn-node-images/storage-ceph/files/scripts/common/pre-load-images.sh, boxes/ncn-node-images/storage-ceph/files/scripts/common/storage-ceph-cloudinit.sh, boxes/ncn-node-images/storage-ceph/files/scripts/metal/lib-1.5.sh
Release 0.2.43.  Contains the following commits:
```
55f0fed (HEAD -> develop, tag: 0.2.43-1, origin/develop, origin/HEAD, origin/CASMINST-3827, CASMINST-3827) CASMINST-3827 - fix container image path for ceph's prometheus
e859c65 CASMINST-3827 - Fix tagging on ceph prometheus image
721149d CASMINST-3825 - Fix a timing issue with ro ceph keyring creation
```
- Fixes CASMINST-3827, CASMINST-3825
=> Release latest prerelease 0.2.43

boxes/ncn-node-images/k8s/files/scripts/common/apply-networking-manifests.sh
- Fixes https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3838
Multus pods sometimes need a force terminate when rolling out a change, this change deletes them if they don't terminate cleanly.
From cloud-init:
```
Wait for Multus Daemonset rollout to complete...
Multus Daemonset rollout is complete.
```
Ran the script during development multiple times
Low risk
=> Add logic to terminate multus pods if they get stuck terminating

boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
Add use_xaddr s3fs option to enable cpe-slurm installs which require extended attributes.
Tested in craystack:
```
ncn-m002:~ # mount | grep s3fs
s3fs on /var/opt/cray/sdu/collection-mount type fuse.s3fs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
s3fs on /var/lib/admin-tools type fuse.s3fs (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
```
```
ncn-m002:~ # cat /etc/fstab
LABEL=SQUASHFS  /  ext4  defaults  0  1
LABEL=CRAYS3CACHE       /var/lib/s3fs_cache     ext4    defaults,nofail,comment=cloudconfig     0       2
sds /var/opt/cray/sdu/collection-mount fuse.s3fs _netdev,allow_other,passwd_file=/root/.sds.s3fs,url=http://ncn-s001:8080,use_path_request_style,use_cache=/tmp,check_cache_dir_exist,use_xattr,uid=2370,gid=2370,umask=0007,allow_other 0 0
admin-tools …
```
=> Modify s3fs mount options to include use_xattr

Jenkinsfile.github, boxes/ncn-node-images/node-images.pkr.hcl
The original intent of this change was to unblock ncn-common (QEMU) build by allowing the GCP upload to happen in parallel with the QEMU upload and subsequent ncn-common build. When changing the order it was discovered that there is a bug in the code where the GCP storage-ceph build downloaded goss test results locally, resulting in the failure of the QEMU storage-ceph build because the output directory already exists.
The order has been changed and the bug has been resolved. The longest part of the build is still the `e4defrag / > /dev/null 2>&1` which appears to give a bit of a benefit on disk size, but more testing is required.
=> CASMINST-3834: Reorganize Jenkinsfile to improve building efficiency.

boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh, boxes/ncn-node-images/storage-ceph/files/resources/common/ansible/ceph-rgw-users/roles/ceph-rgw-users/defaults/main.yml
CASMINST-1850 commit that includes new lib.sh and ansible updates for cluster config-data backup. The changes to ceph-rgw-users include creating new config-data bucket and Config-Data user.  The changes to lib.sh add some conditional logic to configure and sets up the config-data bucket to mount automatically like the ims boot-images bucket but without s3fs cache functions. We do not want to use the caching function for this data and its not necessary.
Doc changes PR opened in `(coming)`
- Fixes CASMINST-1850
- New functionality
Done for the image build for only master nodes. Because this is part of the image build it would not be manually re-run on nodes.
=> CASMINST-1850 commit that includes new lib.sh and ansible updates for cluster config-data backup

boxes/ncn-node-images/k8s/files/resources/common/kubeadm.yaml, boxes/ncn-node-images/k8s/files/resources/common/multus/multus-daemonset.yml, boxes/ncn-node-images/k8s/files/resources/common/vars.sh, boxes/ncn-node-images/k8s/files/resources/common/weave.yaml, boxes/ncn-node-images/k8s/files/scripts/common/kubernetes-cloudinit.sh, boxes/ncn-node-images/k8s/provisioners/common/install.sh, boxes/ncn-node-images/node-images.pkr.hcl, boxes/ncn-node-images/variables.pkr.hcl
Use locally built K8S images that match what's being populated in nexus.
Also tighten permissions on K8S join scripts (CASMINST-3860)
- Fixes https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3799
- Fixes https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3860
Brings alignment between K8S images in nexus and what's being used at bootstrap time.
```
ncn-m003:/etc/cray/kubernetes # ls -l join*
-rwx------ 1 root root 318 Jan 26 21:37 join.sh
```
```
ncn-m002:/etc/cray/kubernetes # ls -l join*
-rwx------ 1 root root 177 Jan 26 21:37 join-command
-rwx------ 1 root root 276 Jan 26 21:37 join-command-control-plane
```
```
ncn-m002:~ # kubectl get pods --all-namespaces -o jsonpath="{..image}" |tr -s '[[:space:]]' '\n' |sort |uniq …
```
=> Reconfigure kube-system docker images to use locally built ones (CASMINST-3799)

boxes/ncn-node-images/k8s/files/resources/common/kubeadm.yaml, boxes/ncn-node-images/k8s/files/resources/common/multus/multus-daemonset.yml, boxes/ncn-node-images/k8s/files/resources/common/vars.sh, boxes/ncn-node-images/k8s/files/resources/common/weave.yaml, boxes/ncn-node-images/k8s/files/scripts/common/kubernetes-cloudinit.sh, boxes/ncn-node-images/k8s/provisioners/common/install.sh, boxes/ncn-node-images/node-images.pkr.hcl, boxes/ncn-node-images/variables.pkr.hcl
- Fixes CASMINST-3860, CASMINST-3799
Contains the following commit:
```
4feac0c (HEAD -> develop, tag: 0.2.47-1, origin/develop, origin/HEAD) Reconfigure kube-system docker images to use locally built ones (CASMINST-3799)
```
=> Latest Pre-release 0.2.47

boxes/ncn-common/files/scripts/common/build-functions.sh, boxes/ncn-common/files/utilities/common/craysys/craysys, boxes/ncn-common/provisioners/google/setup.sh, boxes/ncn-node-images/node-images.pkr.hcl, boxes/ncn-node-images/provisioners/google/cleanup.sh
Google no longer uses the `google-network-daemon` for managing network connections. The build process depended on
this service existing for certain portions. In addition to depending on this service, certain DNS changes were made that are not compatible when the end product is put in place. This update removes the dependency and resets networking configurations. 
- Fixes MTL-1610
- [] I tested this on metal
- [] I tested this on vshasta
=> MTL-1610: Alter GCP specific environment configuration and network settings

boxes/ncn-node-images/storage-ceph/files/scripts/common/csi-configuration.sh, boxes/ncn-node-images/storage-ceph/files/scripts/common/storage-ceph-cloudinit.sh
This will allow us to move the provsioners into ceph-rbd and ceph-cephfs
in order to allow for a configurable upgrade strategy.
Also fixing an issue with the node name for vshasta since it does
not know about the .nmn domain
- Fixes # CASMINST-3857
- Requires #
- Relates to #
enables configuration of upgrade strategy and fixes an issue with cloud-init in vshasta
=> CASMINST-3857 - Fix csi_configuration to support csi-ceph upgrade

boxes/ncn-common/variables.pkr.hcl, boxes/sles15-base/variables.pkr.hcl
Bump kernel to 5.3.18-150300.59.43.1 for CVE.
https://www.suse.com/security/cve/CVE-2022-0185.html
- Fixes MTL-1606
=> MTL-1606: bump kernel version for CVE-2022-0185

boxes/ncn-common/files/scripts/metal/metal-lib.sh
In the previous PR for MTL-1609, a comma was introduced where it
is not needed.  If $efibootmgr_prefix is set, it will already
contain the needed comma.
- Fixes MTL-1609
✅
=> MTL-1609: remove redundant comma

boxes/ncn-common/files/scripts/metal/metal-lib.sh
- Fixes MTL-1614
Release 0.2.51.  This release contains the following commit:
```
448b13f (HEAD -> develop, origin/develop, origin/MTL-1614, origin/HEAD, MTL-1614) MTL-1614: be agnostic about whether CRAY entries are bootable
```
=> Latest Prerelease 0.2.51

Jenkinsfile.github, boxes/sles15-base/base.pkr.hcl, boxes/sles15-base/scripts/kernel.sh, boxes/sles15-base/variables.pkr.hcl
Bump kernel to 5.3.18-24.99.1 to adopt fix for CVE-2022-0185.
https://www.suse.com/security/cve/CVE-2022-0185.html
Fixes [MTL-1607](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1607)
Bugfix Pull Request
=> MTL-1607 Adopt new kernel to fix CVE-2022-0185 [1.0]

boxes/ncn-common/files/resources/common/cloud.cfg
- Fixes CASMINST-3730
This change has been solving the <region>-<hostname> issue for CASMINST-3730. Since adding this into testing with @alexanderkingh on surtur and redbull, we've no longer seen the region hostname appearing during deployments.
=> CASMINST-3730 Disable FQDN hostnames

boxes/ncn-node-images/storage-ceph/files/scripts/common/pre-load-images.sh, boxes/ncn-node-images/storage-ceph/files/scripts/common/storage-ceph-cloudinit.sh, boxes/ncn-node-images/storage-ceph/files/scripts/metal/lib-1.5.sh, boxes/ncn-node-images/storage-ceph/provisioners/common/install.sh
This also bumps ceph-common
This only pre-pulls the image.  it does not install it
- Fixes # CASMPET-5328
- planned upgrade target
This version of ceph contains cve fixes and is based of the centos:stream8 container image
n/a
n/a
=> CASMPET-5328 - Bump ceph upgrade image version

boxes/ncn-common/files/resources/common/cloud/templates/cloud-init-network.tmpl, boxes/ncn-common/files/scripts/metal/net-init.sh
- Fixes CASMINST-3874
- Requires:
https://github.com/Cray-HPE/metal-ipxe/pull/31
https://github.com/Cray-HPE/cray-site-init/pull/122
- Relates to https://github.com/Cray-HPE/node-image-build/pull/141
=>  CASMINST-3874: change lacp-rate from slow to fast; form bond0 in cloud-init

boxes/ncn-common/files/scripts/metal/install.sh, boxes/ncn-common/files/scripts/metal/metal-lib.sh, boxes/ncn-common/files/scripts/metal/net-init.sh
* Make it a hard/fatal error if we can't get the
default route from craysys
* Move the generation of the default route file
into net-init.sh, thus reducing to 1 the number
of times we invoke wicked.
* Move the removal of the 'eth' configs to net-init.sh
prior to reloading interfaces.
* Remove one sleep and reduce the duration of the sleep
after reloading interfaces.
- Fixes CASMINST-3780
=> CASMINST-3780: consolidate wicked actions / harden

boxes/ncn-common/files/resources/common/cloud/templates/resolv.conf.tmpl, boxes/ncn-common/files/scripts/metal/install.sh, boxes/ncn-common/files/scripts/metal/metal-lib.sh, boxes/ncn-common/files/scripts/metal/net-init.sh, boxes/ncn-node-images/storage-ceph/files/scripts/common/pre-load-images.sh, boxes/ncn-node-images/storage-ceph/provisioners/common/install.sh
- Fixes CASMTRIAGE-3006, CASMINST-3780, CASMINST-4052
Contains the following commits:
```
8731c02 (HEAD -> develop, origin/develop, origin/HEAD, origin/CASMINST-3780, CASMINST-3780) Add MIT license
ac54ecf CASMINST-3780: consolidate wicked actions / harden
642f909 shellcheck & formatting cleanup
09862f5 (origin/CASMINST-4052, CASMINST-4052) Fix image path so it will work with nexus
13c2520 Fixing untag for prometheus image
208a30e Fixing prometheus image path
545c7df Update image localtions from arti.dev to arti.algol60
6e74c78 (origin/CASMTRIAGE-3006) CASMTRIAGE-3006: Add options single-request-reopen to resolv.conf
```
=> Latest Pre-release 0.2.58

vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages
- Fixes [CASMTRIAGE-3036](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3036)
This change updates the `csm-rpms` vendored to the latest (`c9507be176fa20a9da0d2c6d2297489e87da8eb9`).  It contains two changes for NCN images:
* updated goss-servers package
* adds `zsh` as an available shell
=> Pre-release of 0.2.60

boxes/ncn-common/provisioners/common/setup.sh, boxes/ncn-node-images/k8s/provisioners/common/install.sh, boxes/sles15-base/http/autoinst.template.xml
* create an empty no.log file so the /var/log/cray/*.log glob
matches at least one file
* remove  nf_conntrack_ipv4, this is deprecated:
```
Mar 02 22:16:13 localhost systemd-modules-load[743]: Failed to find module 'nf_conntrack_ipv4'
```
```
ncn-m002:~ # lsmod | grep -w ^nf_conntrack
nf_conntrack          176128  8 xt_conntrack,nf_nat,xt_state,openvswitch,nf_conntrack_netlink,nf_conncount,xt_MASQUERADE,ip_vs
ncn-m002:~ #
```
- Fixes MTL-1616
=> MTL-1616: fixup broken systemd services

boxes/ncn-node-images/k8s/files/scripts/common/kubernetes-cloudinit.sh
The cert refresh join script runs fine during automation/manual runs, but not via cron since it doesn't know where the kubernetes config file is (non standard location).
* Resolves [CASMTRIAGE-3068](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3068)
```
W0307 17:23:01.641059 4090429 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[upload-certs] Storing the certificates in Secret "kubeadm-certs" in the "kube-system" Namespace
[upload-certs] Using certificate key:
f49d64cca4647a383e9781a08872e58578de3de6b4d9c20e866a495c937c8d55
W0307 17:23:01.884750 4090489 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
```
* …
=> Point token cert refresh script at kube config file

boxes/ncn-common/provisioners/common/install.sh
- Fixes https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3076
Tested on craystack:
```
ncn-m001:~ # grep fuse /etc/containers/storage.conf
mount_program = "/usr/bin/fuse-overlayfs"
ncn-m001:~ # podman ps
CONTAINER ID  IMAGE   COMMAND  CREATED  STATUS  PORTS   NAMES
```
podman not running after 1.2 fresh installs, default config of podman does not use fuse-overlayfs.  This code was tested on wasp and fixed podman/ims tests issue..
Change can be run mutiple times
Low
=> Configure podman so it will run with fuse-overlayfs

boxes/ncn-common/provisioners/common/install.sh
- Fixes [CASMTRIAGE-3076](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3076) - Configure podman so it will run with fuse-overlayfs
=> Pre-release 0.2.64

boxes/ncn-common/files/scripts/metal/metal-lib.sh
CASMTRIAGE-3079 documents an instance of apparent corruption in
the bash execution environment.  As a result, a function with
poor error checking was looping forever.  Add checks for unset
variables and exit with an error if they are unset.
- Fixes MTL-1637
- Relates to CASMTRIAGE-3079
N/A
N/A
=> MTL-1637: harden paginate function

boxes/ncn-common/provisioners/common/setup.sh, boxes/ncn-node-images/k8s/files/tests/metal/goss-image-common.yaml, boxes/ncn-node-images/node-images.pkr.hcl, boxes/ncn-node-images/provisioners/metal/security.sh, boxes/ncn-node-images/storage-ceph/files/tests/metal/goss-image-common.yaml
- Fixes MTL-1647
- Sets default root password to "`*`" in `/etc/shadow`, disabling login as root
- Ensures there are no default ssh keys for root
- Adds build tests to validate the above
- Requires https://github.com/Cray-HPE/docs-csm/pull/1162
=> MTL-1647: remove default root credentials from NC images

boxes/sles15-base/base.pkr.hcl, boxes/sles15-base/variables.pkr.hcl
Addresses an issue of building VirtualBox locally and the disk size not being large enough for the build. This does not impact the QEMU build process, nor the customer release process.
- Fixes [MTL-1649](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1649)
- [] I tested this on metal (e.g. an internal system, with hardware) (x) (if yes, please include results or a description of the test)
=> MTL-1649: Allow VirtualBox build to use larger disk size from initial build.

boxes/ncn-node-images/storage-ceph/files/scripts/common/csi-configuration.sh
Installs of 0.9.x have a cephfs pool name of cephfs_data which if the
csi-configuration.sh is re-run accidentally it will cause manifest failures
due to immutable data in the existing storage class.
- Fixes # CASMTRIAGE-3156
=> Fixing issue with pre csm 1.0 ceph fs pool names and storage classes

boxes/ncn-common/files/scripts/common/chrony/csm_ntp.py, boxes/ncn-common/files/scripts/common/chrony/requirements.txt, boxes/ncn-common/files/scripts/common/chrony/templates/cray.conf.j2
Adds a Python script that an admin can run manually to create and update Chrony configurations on individual nodes.
- Fixes MTL-1664
- Merge with https://github.com/Cray-HPE/docs-csm/pull/1272
This script does not execute without a human manually working with it.
None
=> MTL-1664: Add script to configure and correct chrony.

boxes/ncn-common/common.pkr.hcl, boxes/ncn-common/provisioners/common/csm/ansible.sh, boxes/ncn-node-images/storage-ceph/provisioners/common/install.sh
- Fixes MTL-1660
- Relates to MTL-1513
This moves some of the Ansible init out of storage-ceph and into NCN common.
There is desire to have Ansible everywhere, starting in 1.2.
=> MTL-1660 Add Ansible Virtualenv for CSM

boxes/ncn-common/common.pkr.hcl, boxes/ncn-common/scripts/kernel-debug.sh
- Relates to [MTL-1591](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1591)
Removes the install of kernel-default-debuginfo and kernel-default-debugsource. These will be migrated to the `csm` repo. This significantly reduces the size of the images, and also reduces the build time.
There is a risk that the included RPM does not match the version of the kernel installed. There is an effort to sync these things across all releases.
=> MTL-1591: Remove kernel debug RPMs

boxes/ncn-common/files/scripts/common/create-ims-initrd.sh, boxes/ncn-common/files/scripts/common/create-kis-artifacts.sh
Stop adding xattrs.  They are not needed and cause problems unsquashing
in some contexts (IMS/CFS).
Add a script for creating an initrd that can be used within a container.
- Fixes [CASMINST-4463](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4463)
- Relates to [CASMINST-4462](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4462)
- Transferred the initrd/squash/kernel to from algol60 to hela
- Uploaded to IMS
- Customized squash with IMS
- Created a new initrd using the script in this PR
- Saved the resultant squash/initrd/kernel and transferred them to redbull
- Booted redbull w003 with the resultant artifacts
=> CASMINST-4462: don't use xattrs, add script for creating an initrd

.github/labeler.yml, boxes/ncn-common/files/scripts/common/create-kdump-artifacts.sh
Signed-off-by: Jacob Salmela <jacob.salmela@hpe.com>
- Fixes CASMTRIAGE-3193
- CSM 1.3 enhancements https://github.com/Cray-HPE/node-image-build/pull/236 
- Relates to MTL-1616
In 1.0.x, there is a `ROOTIMG` entry in the node image's `/etc/fstab`.  This LABEL/mount isn't actually used anywhere except for when the image is built (https://stash.us.cray.com/projects/CASM-ARCHIVE/repos/node-image-sles15-base-archive/browse/http/autoinst.template.xml#126-135) as part of autoyast so it is a bit of a misnomer.
```
ncn-m001:~ # blkid -l -t "LABEL=ROOTIMG" -o device
ncn-m001:~ #
```
When the kdump initrd is generated, the kdump dracut module checks the running system for mount points and tries to convert them to kdump mount points.  Namely, it tries it's best to find `/` and …
=> CASMTRIAGE-3193 fix kdump not working

boxes/ncn-node-images/k8s/files/scripts/metal/generate_haproxy_cfg.sh
- Fixes https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3263
Change kube-api haproxy health check from tcp to http, which makes failover more responsive and doesn't hork up postgres.
craystack/surtur
```
Apr 27 14:03:30 ncn-m003 haproxy[16498]: [WARNING] 116/140330 (16498) : Health check for server k8s-api/k8s-api-1 failed, reason: Layer4 connection problem, info: "SSL handshake failure (Connection refused)", check duration: 0ms, status: 1/2 UP.
Apr 27 14:03:41 ncn-m003 haproxy[16498]: [WARNING] 116/140341 (16498) : Health check for server k8s-api/k8s-api-1 failed, reason: Layer7 wrong status, code: 403, info: "HTTP status check returned code <3C>403<3E>", check duration: 895ms, status: 0/2 DOWN.
Apr 27 14:03:41 ncn-m003 haproxy[16498]: [WARNING] 116/140341 …
```
=> Improve kube-api haproxy failover using http instead of tcp check

Jenkinsfile.github
- Fixes MTL-1701
- Relates to MTL-1668
We don't frequently have changes in the base layer, so we limited builds to cease building the base layer through MTL-1668. That code broke the release code, that bug was tracked via MTL-1701. MTL-1701 overzealously ceased publishing the 
common layers, which do frequently have changes. This change ensures those are always published.
Feature Branch Example
Git Tag Example (0.3.2-6 was taken on this branch as a test and then deleted)
=> MTL-1701 Restore publishing the common layer

Jenkinsfile.github, boxes/ncn-common/common.pkr.hcl, boxes/ncn-common/files/scripts/google/cloudinit.sh, boxes/ncn-common/files/scripts/google/update-dns.py, boxes/ncn-common/files/utilities/common/craysys/craygoogle.py, boxes/ncn-common/provisioners/google/pyenv.sh
- Fixes [MTL-1684](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1684)
Previously `requests` was being installed with the system python. This was removed. A new virtual environment was added specifically for scripts executed in the GCP environment that needed the installation of requests. 
This will later be amended by [MTL-1673](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1673) when a standard is established for adding and using virtual environments with Ansible. This PR just finishes the work started in [MTL-1668](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1668)
=> MTL-1684 - Create python virtual environment for gcp scripts

.github/workflows/merge-strategy.yml
Fixes csm-rpms updates if they contain multiple changed files.
The issue was that the plugin we used had the `/g` flag on the regex, which remembers the previous matched index. This caused the regex to flip between true and false undesirably.
=> Allow slashes on the vendor dir

boxes/ncn-common/files/scripts/common/chrony/csm_ntp.py, boxes/ncn-common/files/scripts/common/chrony/templates/cray.conf.j2
- Fixes MTL-1698
- Fixes MTL-1697
- Relates to CASMINST-4413
Improves error handling of NTP script.  Specifically for situations when BSS is not installed/available.  Also adjusts the template path to the correct value.
Also adds two config options to enable remote chronyc commands.
Ran again and again and the config stayed the same
Low.
=> MTL-1697 MTL-1698

.github/workflows/shellcheck.yml, boxes/ncn-common/files/scripts/common/build-functions.sh, boxes/ncn-common/files/scripts/common/create-kis-artifacts.sh
Signed-off-by: Jacob Salmela <jacob.salmela@hpe.com>
- Partially implements MTL-1497
Adds a shellcheck github action, limited in scope to a single folder for now.  Also adjusts two scripts with a minor change to appease the linter.
Just runs shellcheck during builds
Low.
=> add shellcheck github action

boxes/ncn-common/files/scripts/common/chrony/templates/cray.conf.j2
Signed-off-by: Jacob Salmela <jacob.salmela@hpe.com>
- Fixes CASMTRIAGE-3336
This restores the template to what we had been using.  It was slightly modified when we transitioned to this script.  It was missing the `initstepslew` directive.  I also added `prefer` as it allowed the nodes to quiesce much faster when rapidly changing configurations.
- `#redbull`
I booted the nodes and ran through the documented procedure.
```
redbull-ncn-m001-pit:/var/www/ncn-w003 # for i in $(grep -oP 'ncn-\w\d+' /etc/dnsmasq.d/statics.conf | sort -u | grep -v ncn-m001); do ssh $i "chronyc waitsync 6 0.5 0.5 10"; done
Warning: Permanently added 'ncn-m002,10.252.1.5' (ECDSA) to the list of known hosts.
try: 1, refid: 0AFC0104, correction: 0.000010350, skew: 0.577
try: 2, refid: 0AFC0104, …
```
=> CASMTRIAGE-3326 add prefer to chrony config, update template

boxes/ncn-common/files/resources/common/cloud/templates/sshd_config.tmpl, boxes/ncn-common/files/scripts/metal/net-init.sh
- Fixes [CASMNET-1549](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1549)
Allows access to sshd on any network that is not CHN and CAN.
=> CASMNET-1549: Add sshd_config cloud-init step and template

boxes/ncn-node-images/storage-ceph/files/scripts/common/pre-load-images.sh
- Fixes # CASMINST-4682
Adding tag to existing image that was missed during the change from pulling upstream containers to algol60
n/a
n/a
=> Fixing image path for ceph prometheus container to fix goss test

boxes/ncn-node-images/k8s/files/resources/common/kubeadm.cfg, boxes/ncn-node-images/k8s/files/resources/common/tenant-admin.conf, boxes/ncn-node-images/k8s/files/scripts/common/kubernetes-cloudinit.sh, boxes/ncn-node-images/k8s/files/scripts/google/lib.sh, boxes/ncn-node-images/k8s/files/scripts/metal/lib.sh
- Fixes https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4301
Add api-server integration for OIDC multi-tenancy, as well as provide kubectl config file for tenant-admin use.
```
ncn-m001:~ # kubectl get nodes
NAME       STATUS   ROLES                  AGE   VERSION
ncn-m001   Ready    control-plane,master   35m   v1.20.13
ncn-m002   Ready    control-plane,master   34m   v1.20.13
ncn-m003   Ready    control-plane,master   34m   v1.20.13
ncn-w001   Ready    <none>                 34m   v1.20.13
ncn-w002   Ready    <none>                 34m   v1.20.13
ncn-w003   Ready    <none>                 34m   v1.20.13
```
This will fix fresh install -- still need same change for upgrade (not image change).
Low
=> Add OIDC api-server integration for multi-tenancy

boxes/ncn-common/files/resources/common/cloud/templates/metal-iptables.conf.tmpl, boxes/ncn-common/files/resources/metal/sshd_config, boxes/ncn-common/files/resources/metal/systemd/metal-iptables.service, boxes/ncn-common/files/scripts/metal/net-init.sh, boxes/ncn-common/provisioners/metal/setup.sh
- Fixes [CASMNET-1549](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1549)
- Fixes [CASMNET-1568](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1568)
When the NCN is built,  the service is placed on the machine and enabled. The NCN boots, cloud-init kicks off net-init and the iptables_config function puts the iptables file into place, based on the BSS metadata for the networks. This template blocks on CAN and CHN networks. After cloud-init is done, the system finishes booting and the service is executed, which loads the iptables rules that work and allow 22 traffic destined for k8s. 
This was tested on Redbull and Mug.
Mug: The rules were loaded on all worker nodes and access was verified for UAI. We confirmed that ssh to the interface's IP was not …
=> CASMNET-1549: Add iptables rules and service for ssh

boxes/ncn-common/files/tests/common/goss-image-common.yaml, boxes/ncn-common/provisioners/common/install.sh
goss-servers starts on boot, but is not enabled. Fix that.
- Fixes CASMTRIAGE-3391
=> CASMTRIAGE-3391: enable goss-servers

boxes/ncn-common/common.pkr.hcl, boxes/ncn-common/provisioners/common/install.sh, boxes/ncn-common/provisioners/google/setup.sh, boxes/ncn-node-images/kubernetes/provisioners/common/install.sh, boxes/pit-common/pit-common.pkr.hcl, boxes/pit-common/provisioners/google/setup.sh, vendor/github.com/Cray-HPE/csm-rpms/Jenkinsfile.github, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/google.packages
Create /etc/cray/kubernetes/version with the KUBERNETES_PULL_VERSION variable. This file is necessary for kubernetes-cloudinit.sh for creating kubeadm.yaml. This file might be used in other places, so this change ensures that the version file still exists.
Without this change the `kubernetesVersion:` is incorrect in the kubeadm.yaml file:
```yaml
ncn-m002:~ # cat /etc/cray/kubernetes/kubeadm.yaml
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
certificateKey: "ce28c44b12f1231038558a2218d2ca10c674c132fd9777b6419fd5806eda4456"
localAPIEndpoint:
advertiseAddress: "10.252.1.5"
bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: "v"
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: "10.252.1.2:6442" …
```
=> MTL-1790 Fallout

boxes/pit-common/provisioners/common/install.sh, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/repos/suse.template.repos
This updates the LiveCD, pulling kubectl in via csm-rpms instead of an ad-hoc install.
The ensures kubectl is the same version, assuming it's updated in csm-rpms appropriately.
This pairs with:
- https://github.com/Cray-HPE/cray-pre-install-toolkit/pull/35
- https://github.com/Cray-HPE/csm-rpms/pull/452
This also brings in an ancillary change: https://github.com/Cray-HPE/csm-rpms/pull/453
=> MTL-1796 update pit common

Jenkinsfile.github
- Fixes MTL-1799
- Relates to CASMINST-4793
csm-images now requires authentication to read due to the CASMINST-4793 security scramble. This change downloads the base images to a local directory using curl. Curl was used because packer can't handle authentication headers.
**This change is required to fix NCN image builds.**
=> MTL-1799 SECURITY SCRAMBLE

boxes/ncn-node-images/kubernetes/files/resources/metal/cloud.cfg.d/00_metalfs_lvm.cfg, boxes/ncn-node-images/storage-ceph/files/resources/metal/cloud.cfg.d/00_metalfs_lvm.cfg
- Fixes MTL-1798
This passes `-y` to the `lvcreate` calls to ensure that if any signatures are found on an old LVM that they're clobbered.
This will remove/silence the benign (see JIRA) errors emitted during cloud-init runtime.
Example of this succeeding on a storage node:
```bash
Physical volume "/dev/md/AUX" successfully created.
Volume group "metalvg0" successfully created
Wiping ext4 signature on /dev/metalvg0/CEPHETC.
Logical volume "CEPHETC" created.
Wiping ext4 signature on /dev/metalvg0/CEPHVAR.
Logical volume "CEPHVAR" created.
Wiping xfs signature on /dev/metalvg0/CONTAIN.
Logical volume "CONTAIN" created.
```
Example of this succeeding on a kubernetes node:
```bash
Physical volume "/dev/md/AUX" successfully created.
Volume group "metalvg0" successfully …
```
=> MTL-1798 Ensure lvcreate clobbers any old signatures

boxes/ncn-node-images/kubernetes/files/tests/common/goss-image-common.yaml, boxes/ncn-node-images/kubernetes/files/tests/metal/goss-image-common.yaml, boxes/ncn-node-images/storage-ceph/files/tests/common/goss-image-common.yaml
- Fixes unmarshal errors in goss test for ensuring that no root password exists in /etc/shadow on ncn images
goss tests are idempotent
=> added regex in goss test for no root password check

vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-kubernetes/metal.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/metal.packages, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/files/srv/cray/resources/metal/mdadm.conf
This brings in two vendor updates:
- `mdadm.conf` change from https://github.com/Cray-HPE/metal-provision/pull/8
- `dracut-metal` RPMs from https://github.com/Cray-HPE/csm-rpms/pull/464
The changes fix the MTL-1288 bug for the auto-wipe.
=> MTL-1288 Auto-wipe Fix

Jenkinsfile.github, boxes/ncn-node-images/kubernetes/files/tests/common/goss-image-common.yaml, boxes/ncn-node-images/kubernetes/files/tests/metal/goss-image-common.yaml, boxes/ncn-node-images/storage-ceph/files/tests/common/goss-image-common.yaml, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-kubernetes/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-kubernetes/metal.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/metal.packages, vendor/github.com/Cray-HPE/csm-rpms/repos/cray.repos, vendor/github.com/Cray-HPE/metal-provision/.github/workflows/lint.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-install/defaults/main.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-install/tasks/common.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-install/tasks/gcp.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-install/tasks/metal.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/defaults/main.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/files/srv/cray/resources/metal/mdadm.conf, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/files/srv/cray/tests/common/goss-image-common.yaml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/files/srv/cray/tests/metal/goss-image-common.yaml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/tasks/gcp.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/tasks/metal.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-team/defaults/main.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-team/tasks/common.yml
- d11340f00 (HEAD -> develop, tag: 0.3.10-4, tag: 0.3.10, origin/develop, origin/MTL-1288, origin/HEAD, MTL-1288) Update "csm-rpms" from "git@github.com:Cray-HPE/csm-rpms.git@main"
- a9493b742 Squashed 'vendor/github.com/Cray-HPE/csm-rpms/' changes from 982cb3af2..865ec55b2
- ed3bd0f16 Update "metal-provision" from "git@github.com:Cray-HPE/metal-provision.git@v1.0.2"
- f059d7856 Squashed 'vendor/github.com/Cray-HPE/metal-provision/' changes from 4cc1fd9e5..43e9e3cb9
- 93e017435 Squashed 'vendor/github.com/Cray-HPE/csm-rpms/' changes from b6f19bb9e..982cb3af2
- 6c2d9ddb5 (tag: 0.3.10-3, origin/csm-rpms-update-2, csm-rpms-update-2) Update "csm-rpms" from "git@github.com:Cray-HPE/csm-rpms.git@main"
- 7d569f5ea (origin/root-goss-test-fix, …
=> Latest 0.3.10 Release

vendor/github.com/Cray-HPE/metal-provision/.github/PULL_REQUEST_TEMPLATE.md, vendor/github.com/Cray-HPE/metal-provision/.github/workflows/shellcheck.yml, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/files/srv/cray/scripts/common/cleanup-kis-artifacts.sh, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/files/srv/cray/scripts/common/create-ims-initrd.sh, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/files/srv/cray/scripts/common/create-kdump-artifacts.sh, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/files/srv/cray/scripts/common/create-kexec-initrd.sh, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/files/srv/cray/scripts/common/create-kis-artifacts.sh, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/files/srv/cray/scripts/common/dracut-lib.sh
**This requires https://github.com/Cray-HPE/metal-provision/pull/10 to merge first, if more changes are made to that PR then this PR requires a rebuild/redo.**
- Fixes: MTL-1761
We often repeat static inputs to dracut in our scripts, this adds a library and updates the following scripts to use the library:
- `create-ims-initrd.sh`
- `create-kdump-artifacts.sh`
- `create-kexec-initrd.sh`
- `create-kis-artifacts.sh`
Each script was tested on metal to verify that the modifications worked.
Lastly this also resolves an old problem where a mount point would exist after running `create-kis-artifacts.sh`:
```bash
redbull-ncn-m001-pit: # mount | grep 'squashfs-root'
/dev/sdd4 on /var/www/ephemeral/data/k8s/0.3.12/squashfs-root/mnt/squashfs type ext4 (rw,noatime) …
```
=> MTL-1761 Use new dracut-lib.sh

boxes/pit-common/pit-common.pkr.hcl, boxes/pit-common/provisioners/common/install.sh, boxes/pit-common/provisioners/common/setup.sh
- Fixes: MTL-1820
This was fixed in cray-pre-install-toolkit, this PR is ensuring that pit-common doesn't drift from what's in cray-pre-install-toolkit.
=> MTL-1820 Sync aliases from cray-pre-install-toolkit

vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-kubernetes/metal.packages
- Relates to: MTL-1748 & CASMTRIAGE-3640
Pulls in two changes:
- CASMTRIAGE-3640 (not used) for pit-common (see: https://github.com/Cray-HPE/cray-site-init/pull/201)
- MTL-1748 REVERT for fixing LUKS disks on NVME (see: https://github.com/Cray-HPE/dracut-metal-luksetcd/pull/36)
=> MTL-1748 Revert and Benign Include of CASMTRIAGE-3640

Jenkinsfile.github
Remove manual steps admins must complete for publishing base and pit-common.
Reword parameter descriptions.
This'll remove risk of an administrator forgetting to cancel or not canceling a git-tag build in time before it publishes anything _in_ the case they want to publish a base image.
The current problem is that if a base or pit-common image must be published, an Administrator must race to the tag build and be ready to cancel it after it has pulled the Jenkinsfile and enabled "Build with Parameters." Then the administrator can toggle publishing base or pit-common. If the admin. is too late, they have to cleanup builds already published into GCP (since GCP doesn't allow overwrite). If an admin. is too early, the build won't have scanned the Jenkinsfile and won't have …
=> MTL-1837 Try/catch publishes to base & pit-common

vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/metal.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/metal.packages
- Fixes: CASMINST-4914
Adds `kernel-firmware`, allowing NIC adapters to be viewable on QLogic equipped systems.
=> CASMINST-4914 kernel firmware

boxes/ncn-node-images/storage-ceph/files/scripts/google/lib.sh, boxes/pit-common/provisioners/google/setup.sh, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/files/srv/cray/scripts/google/cloudinit.sh, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common-setup/tasks/gcp.yml
- Fixes: vshasta
- Requires:
- Relates to:  VSHA-403
disabling cronjob that overwrites authorized_keys
This introduces some risk since this change also brings in a newer version of X, but otherwise the original bugfix
is resolved and the overall risk of fatal failures is reduced.
=> VSHA-403 Add sleep

boxes/ncn-common/provisioners/google/setup.sh
At one point in git history, this file contained an SSH key.
When the repo was scrubbed to remove that from history, it ended
up removing the file entirely. This commit adds it back, as it
was at lts/csm-1.2 HEAD prior to the repo scrub.
=> Re-introduce google/setup.sh

boxes/ncn-node-images/kubernetes/files/resources/common/vars.sh, boxes/ncn-node-images/kubernetes/provisioners/common/install.sh
https://jira-pro.its.hpecorp.net:8443/browse/MTL-1840
- Fixes: MTL-1840
Installs kata containers bundled with qemu-system-x86_64. This does not include dependencies for running ARM environments.
Idempotency will come when porting to ansible. Currently there isn't any ansible framework in place for worker and storage nodes. 
The Kata environment is self-contained and doesn't present any risks to the existing environment.
=> MTL-1840 install kata containers, bundled with qemu-system-x86_64

boxes/ncn-common/provisioners/common/install.sh, boxes/pit-common/provisioners/common/install.sh, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/metal.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/metal.packages
- Fixes: MTL-1853
Ensures only the kernel listed in csm-rpms (`kernel-default`) is installed. Purges all other kernels.
This does mean that `kexec` needs to update this value in `/etc/zypper/zypp.conf` and also run `purge-kernels`. The `zypp.conf` update will allow a new kernel to install, and the `purge-kernels` keeps things tidy (and maybe is undesired).
Example output:
```bash
+ kernel
+ local current_kernel
++ grep kernel-default /srv/cray/csm-rpms/packages/node-image-non-compute-common/base.packages
++ awk -F = '{print $NF}'
+ current_kernel=5.3.18-150300.59.76.1
Purging old kernels ...
+ echo 'Purging old kernels ... '
+ sed -i 's/^multiversion.kernels =.*/multiversion.kernels = 5.3.18-150300.59.76.1/g' /etc/zypp/zypp.conf
+ zypper --non-interactive …
```
=> MTL-1853 Lock to csm-rpms kernel

boxes/ncn-common/provisioners/common/install.sh, boxes/ncn-node-images/kubernetes/files/scripts/common/kubernetes-cloudinit.sh, boxes/pit-common/provisioners/common/install.sh, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/cray-pre-install-toolkit/metal.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/base.packages, vendor/github.com/Cray-HPE/csm-rpms/packages/node-image-non-compute-common/metal.packages
Fix extension for renamed file
- Fixes: https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5037
Adapt to new kubeadm.yaml file name
```
ncn-m001:/srv/cray/scripts/kubernetes # ./token-certs-refresh.sh
[upload-certs] Storing the certificates in Secret "kubeadm-certs" in the "kube-system" Namespace
[upload-certs] Using certificate key:
878f4d424f294ac5c3698eadfb2a7dc3fe8e5c2da154bbd4390dd82378d3fc12
```
N/A
Low
=> CASMINST-5037 Fix extension for kubeadm file in token refresh script

boxes/ncn-node-images/kubernetes/files/resources/common/encryption-configuration.yaml, boxes/ncn-node-images/kubernetes/files/resources/common/kubeadm.cfg, boxes/ncn-node-images/kubernetes/files/scripts/common/kubernetes-cloudinit.sh
This setup just basically turns on the encryption configuration
machinery in a default identity way. This means nothing has actually
changed as we're not using any encryption but we want this in place for
further changes.
- Relates to: CASMINST-5130
This change enables the encryption provider for kubernetes/kubeadm. This initial commit for cloud init only enables it as a passthrough or identity configuration. So essentially this is a no op, but the directory created is used by a new DaemonSet to read configuration data from the current.yaml symlink.
Ran the added function setup-encryption multiple times. Its rather short so hard to not make idempotent.
As its a control plane change always a chance this introduces issues I'm not aware of booting k8s on bare metal. …
=> CASMINST-4521: Add kubeadm identity configuration

boxes/ncn-node-images/kubernetes/files/resources/common/encryption-configuration.yaml, boxes/ncn-node-images/kubernetes/files/resources/common/kubeadm.cfg, boxes/ncn-node-images/kubernetes/files/scripts/common/kubernetes-cloudinit.sh
This reverts commit ffdec40f08149b362ac624c90b07755fe8250564.
I got this to boot but restarting kubelet had issues. Instead of holding up others just revert this and I can test/validate on redbull myself.
- Fixes:
- Requires:
- Relates to:
=> Revert "CASMINST-5130: Add kubeadm identity configuration"

.github/pr-branch-labeler.yml, README.adoc
Since there is no more `develop` branch, there's no need to mark PRs to `main` as "release".
Signed-off-by: Russell Bunch <doomslayer@hpe.com>
=> Do not mark `main` as release

boxes/ncn-node-images/kubernetes/files/resources/common/encryption-configuration.yaml, boxes/ncn-node-images/kubernetes/files/resources/common/kubeadm.cfg, boxes/ncn-node-images/kubernetes/files/scripts/common/kubernetes-cloudinit.sh
Fixes for the issues seen with the smoketest
- Fixes: CASMINST-5130
- Requires:
- Relates to:
Reverts the revert and fixes the issues seen with redbull.
- [x ] I tested this on internal system redbull, I pulled in the images and then rebooted both nodes and ensured we can cloud-init into k8s successfully. I tested out a couple other scenarios aka restarting kubelet after etc...)
n/a
Need the kubeadm.cfg changes in so they can be used by a daemonset that mounts the directory they are in. As well as need the volume mounts in place for the kubeapi so that we can make it possible to add api encryption on the fly without node image changes.
=> CASMINST-5130

boxes/ncn-common/provisioners/common/cleanup.sh, boxes/ncn-node-images/node-images.pkr.hcl, vendor/github.com/Cray-HPE/metal-provision/roles/ncn-common/files/tests/common/ncn-common-tests.yml
- Fixes: MTL-1905
`zypper purge-kernels` was failing because when it's invoked there's a `zypper lock` on `kernel-default`. The lock prevents `purge-kernels` from actually purging undesirable kernels.
This also adds a test to ensure we do not hit this again.
=> MTL-1905 single kernel

Jenkinsfile.github
- Relates to: #448 
Remove incorrect, `when` clause for the base layer. It was breaking anything but it doesn't make any sense.
Forgot to define `source` for PIT and NCN builds when they do rebuild the base layer.
=> Minor adjustments

Jenkinsfile.github
- Fixes:
- Requires:
- Relates to: #448 #451 
Deposit into pre-install-toolkit, not pit.
I had cleaned up Artifactory yesterday for 1.3 and 1.4 but forgot to fixup this line.
Main's PR is coming via MTL-1910.
=> Deposit into pre-install-toolkit

boxes/ncn-node-images/kubernetes/files/tests/common/kubernetes-tests.yml, boxes/ncn-node-images/kubernetes/provisioners/common/install.sh, boxes/ncn-node-images/storage-ceph/files/tests/common/storage-ceph-tests.yml
Ensure kata and containerd tarball unpack with root ownership, add goss test to confirm
- Fixes: MTL-1906
=> MTL-1906: ensure kata and containerd tarball unpack with root ownership

Jenkinsfile.github, boxes/ncn-node-images/kubernetes/provisioners/common/install.sh
- Relates to: MTL-1910
`packer init` was added to ensure we always have the right plugins installed, but running `packer init` in `parallel {}` Jenkins blocks proves to cause problems.
This change runs a single `packer init` at the beginning of the build, removing `packer init` from each layer.
This problem has been encountered following the merge of #464 , but it was not encountered during #464's builds since that PR build a base layer and invoked `packer init` then. The subsequent `packer init` calls never had to do anything since the plugins were already installed. This problem is coming about quite often now that we begin with the ncn-node-image layer and run `packer init` in parallel.
=> MTL-1910 Remove extra `packer init` calls
